var makeCollections = require('./base.js')
	, models = require('./schema.js')
	, mysql = require('mysql')
	, _ = require('underscore')
	, async = require('async')
;

var db = mysql.createClient({
	user: 'eq',
	password: 'hjvfirf',
	host: '127.0.0.1',
	port: 3306,
	database: 'dossee'
});

var all = makeCollections(db, models);
function main(autocb){
	var err, institutes;
  await {
  	all.institutes(defer(err, institutes));
  }
	_.each(institutes, function(n){
	});
	for(var i = 0; i < institutes.length; i++){
		var institute = institutes[i]
			, err1
			, students
		;	
		console.log('~~~~~~~~');
		console.log(institute.name);
		console.log('~~~~~~~~');
		await {
			institute.students(defer(err1, students));
		}

		for(var j = 0; j < students.length; j++){
			console.log(students[j].fullname());
		}
	}
}
main(function(){
	db.end();
});

